language: c
sudo: required
dist: trusty
os:
  - linux
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install cmake -y
  - ./.travis-install-cmocka.sh

script: ./bootstrap && ./configure && make && make check
